excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- RxProject/AppDelegate.swift
- RxProjectTests

disabled_rules: # rule identifiers to exclude from running
- line_length
- identifier_name
- trailing_whitespace
- shorthand_operator
#- colon
